pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps{
                sh 'cd mi-proyecto && mvn clean install'
            }
        }
        stage('Test') {
            steps{
                sh 'cd mi-proyecto && mvn test'
            }
        }
        stage('Deploy') {
            steps{
                echo 'Deploying... prueba trigger'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
        success {
            echo 'Pipeline succeeded.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
